# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec27a3ee756fdd57a05a48f93494caea4f1b12035aaeb630630b3cac7e0f174b21665d10f346655001234a9121fa1273e7ad1d759c521d41753c6376d75d5ee

test:
  secret_key_base: fb97adb81bfea0033dd233f644729378d7d89e79dd004a99e81626596ea4533f84055499fe84e4cce36ab121a3d8c41acb33988f2ed45d962f0e8229c67b2079

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
